services:
  - type: web
    plan: free
    name: AutoAcceptBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Snowball-0/Auto-Accept-Telegram-Bot
    branch: master
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SESSION
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_URL
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
